config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :news
  resources :users
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :news
  accepts_nested_attributes_for :news
end

app/models/news.rb
class News < ApplicationRecord
  has_many :comments

  validates_presence_of :author
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]


  # GET /comments
  # GET /comments.jsons
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to request.referrer, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :content, :published, :news_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @news = News.all.order(created_at: :desc)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all.order(created_at: :desc)
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @comment = Comment.new
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :subtitle, :body, :published, :active, :author)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username, :email, :password, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :published %>
    <%= f.date_select :published %>
  </div>

  <div class="field">
    <%= f.label :news_id %>
    <%= f.text_field :news_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Content</th>
      <th>Published</th>
      <th>News</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.content %></td>
        <td><%= comment.published %></td>
        <td><%= comment.news %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <%= render 'form', comment: @comment %>
  </div>
</div>
<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Published:</strong>
  <%= @comment.published %>
</p>

<p>
  <strong>News:</strong>
  <%= @comment.news %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.erb
<div class="container">
  <div class="alert alert-info text-center" role="alert">
    Ultimas Noticias
  </div>
  <div class="row">
    <% @news[0..9].each do |news| %>
        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
          <article class="">
            <h5><%=link_to news.title, news %></h5>
            <div class="summary">
              <% if news.subtitle.length > 249 %>
                  <%= news.subtitle[0..249] + "..." %>
              <% else %>
                  <%= news.subtitle %>
              <% end %>
              <% if news.comments.count > 0 %>
                  <a href="#" title="<%= news.comments.count %> Comentarios">
                    <span class="badge"><%= news.comments.count %></span></a><br>
              <% end %>
          </article>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IIC3103 - Sitio de Noticias en Ruby</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">IIC3103 News</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="active">
        <a href="/"><span class="glyphicon glyphicon-globe"></span> Noticias</a>
      </li>
      <li class="active">
        <a href="/news"><span class="glyphicon glyphicon-edit"></span> Adminstrar</a>
      </li>
    </ul>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/news/_comment_form.html.erb
<%= form_for(comment) do |f| %>
    <%= f.hidden_field :news_id, :value => @news.id %>
    <div class="form-group">
      <label for="author">Nombre</label>
      <div class="field">
        <%= f.text_field :author %>
      </div>
      <label for="content">Comentario</label>
      <div class="field">
        <%= f.text_area(:content, :rows => 5, :class => 'form-control') %>
      </div>

    </div>
    <button class="btn btn-primary" type="submit">Crear Comentario</button>
<% end %>

app/views/news/_form.html.erb
<%= form_for(news) do |f| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Titulo</label>
    <div class="field">
      <%= f.text_field(:title, :class => 'form-control') %>
    </div>
    <br>
    <label>Bajada</label>
    <%= f.text_area(:subtitle, :rows => 4, :class => 'form-control') %>
    <br>

    <label>Cuerpo</label>
    <%= f.text_area(:body, :rows => 7, :class => 'form-control') %>
    <br>

    <label>Author</label>
    <%= f.text_field(:author, :class => 'form-control') %>
    <br>

    <button class="btn btn-primary" type="submit">Actualizar</button>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Noticias</h1>
  <button type="button" class="btn btn-success"><%= link_to 'Nuevo', new_news_path %></button>
  <div class="row">
    <div class="col-sm-12">
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th>Titulo</th>
            <th class="hidden-xs">Bajada</th>
            <th class="hidden-xs">Conteudo</th>
            <th class="hidden-xs">Fecha Publicacion</th>
            <th class="hidden-xs">Activo</th>
            <th class="hidden-xs">Autor</th>
            <th colspan="3"></th>
          </tr>
          </thead>
          <tbody>
          <% @news.each do |news| %>
              <tr>
                <td><%= news.title[0..30] %><%= link_to '...', news %></td>
                <td class="hidden-xs"><%= news.subtitle[0..200] %><%= link_to '...', news %></td>
                <td class="hidden-xs"><%= news.body[0..400] %><%= link_to '...', news %></td>
                <td class="hidden-xs"><%= news.created_at %></td>
                <td class="hidden-xs"><%= news.active %></td>
                <td class="hidden-xs"><%= news.author %></td>

                <td>
                  <button type="button" class="btn btn-info"><%= link_to 'abrir', news %></button>
                </td>
                <td>
                  <button type="button" class="btn btn-warning"><%= link_to 'alterar', edit_news_path(news) %></button>
                </td>
                <td>
                  <button type="button" class="btn btn-danger"><%= link_to 'remove', news, method: :delete, data: {confirm: 'Are you sure?'} %></button>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/news/new.html.erb
<h1>Crear Noticia</h1>
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <%= render 'form', news: @news %>
  </div>
</div>
<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1> <%= @news.title %> </h1>
      <div>
        por <span class="label label-default"><%= @news.author %></span> en <span><%= @news.created_at %></span>
      </div>
      <br>
      <div class="summary"><%= @news.subtitle %></div>
      <br>
      <% len = @news.body.length %>
      <% if len > 1000 %>
          <div class="content">
            <span><%= @news.body[0..999] %></span><span id="body_hidded" style="display:none;"><%= @news.body[1000..len-1] %></span>
            <span id="body_view_more"><a href="javascript:view_element('body_hidded', 'body_view_more');">...ler mas</a></span>
          </div>


      <% else %>
          <div class="content">  <%= @news.body %></div>

      <% end %>
    </div>
    <div class="col-md-2"></div>
  </div>
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-10">
      <h2>Comentarios</h2>
      <% @news.comments.each do |comment| %>
          <div class="media">
            <div class="media-left media-top">
              <a href="#">
                <%= image_tag("user.jpg", border: 0) %> </a>
            </div>
            <div class="media-body">
              <h4 class="media-heading"><%= comment.author %></h4>
              <%= comment.content %>
            </div>
          </div>
      <% end %>
      <br>
    </div>
    <div class="col-xs-1"></div>
  </div>
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-10">
      <div class="panel panel-default">
        <div class="panel-heading">Comentar</div>
        <div class="panel-body">
          <%= render 'comment_form', comment: @comment %>
        </div>
      </div>
    </div>
    <div class="col-xs-1"></div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.active %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Active:</strong>
  <%= @user.active %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>